import esbuild from "esbuild";

const production = process.argv.includes("production");
const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner: {
    js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */"
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@homebridge/node-pty-prebuilt-multiarch",
    "child_process",
    "crypto",
    "fs",
    "os",
    "path"
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production
});

if (watch) {
  await context.watch();
  console.log("Watching for changes...");
} else {
  await context.rebuild();
  await context.dispose();
}
